// packages/battleship-react/src/hooks/grid.ts
import { useMemo, useState } from "react";
import { Cell, Grid } from "battleship-core";

export function useGrid() {
  const gridSize = 10;
  const [grid, setGrid] = useState(new Grid(gridSize));

  const displayableGrid = useMemo(() => {
    return grid.toDisplayableGrid();
  }, [grid]);

  function shoot(cell: Cell) {
    grid.shoot(cell.position);
    setGrid(Object.assign(new Grid(gridSize), grid));
  }

  return { grid, displayableGrid, shoot };
}

// packages/battleship-solid/src/signals/grid.ts
import { Cell, Grid } from "battleship-core";
import { createSignal } from "solid-js";

const gridSize = 10;
const initial = new Grid(gridSize);

export function useGrid() {
  const [grid, setGrid] = createSignal(initial);

  const displayableGrid = () => {
    console.log(grid());
    return grid().toDisplayableGrid();
  };

  function shoot(cell: Cell) {
    initial.shoot(cell.position);
    setGrid(Object.assign(new Grid(gridSize), initial));
  }

  return { displayableGrid, shoot };
}
