// packages/battleship-react/src/components/Grid.tsx
import { useGrid } from "../hooks/grid";
import Cell from "./Cell";

function Grid() {
  const { displayableGrid, shoot } = useGrid();

  const click = (cell: any) => shoot(cell);

  return (
    <>
      {displayableGrid &&
        displayableGrid.map((row, i) => {
          return (
            <div className="rows" key={i}>
              <span className="header">{row[0].position.x}</span>
              {row.map((cell) => {
                return (
                  <div key={cell.position.y}>
                    {i === 0 ? (
                      <span className="header">{cell.position.y}</span>
                    ) : null}
                    <Cell cell={cell} click={click}></Cell>
                  </div>
                );
              })}
            </div>
          );
        })}
    </>
  );
}

export default Grid;

// packages/battleship-vue/src/components/Grid.vue
<script setup lang="ts">
import Cell from './Cell.vue'
import { useGridStore } from '../stores/grid'
const store = useGridStore()
</script>

<template>
  <div class="rows" v-for="(row, i) in store.displayableGrid">
    <span class="header">{{ row[0].position.x }}</span>
    <div class="cell" v-for="cell in row">
      <span class="header" v-if="i === 0">{{ cell.position.y }}</span>
      <Cell :cell="cell" />
    </div>
  </div>
</template>

<style scoped>
.rows {
  display: flex;
  flex-direction: row;
}
.header {
  height: 20px;
  width: 20px;
  align-self: center;
  justify-self: center;
}
</style>
