// packages/battleship-react/src/components/Grid.tsx
import { useGrid } from "../hooks/grid";
import Cell from "./Cell";

function Grid() {
  const { displayableGrid, shoot } = useGrid();

  const click = (cell: any) => shoot(cell);

  return (
    <>
      {displayableGrid &&
        displayableGrid.map((row, i) => {
          return (
            <div className="rows" key={i}>
              <span className="header">{row[0].position.x}</span>
              {row.map((cell) => {
                return (
                  <div key={cell.position.y}>
                    {i === 0 ? (
                      <span className="header">{cell.position.y}</span>
                    ) : null}
                    <Cell cell={cell} click={click}></Cell>
                  </div>
                );
              })}
            </div>
          );
        })}
    </>
  );
}

export default Grid;

// packages/battleship-solid/src/components/Grid.tsx
import { For, Show } from "solid-js";

import { useGrid } from "../signals/grid";
import Cell from "./Cell";

function Grid() {
  const { displayableGrid, shoot } = useGrid();

  const clickCell = (cell: any) => shoot(cell);
  return (
    <>
      <For each={displayableGrid()}>
        {(row, i) => (
          <div class="rows">
            <span class="header">{row[0].position.x}</span>
            <For each={row}>
              {(cell) => (
                <div>
                  <Show when={i() === 0}>
                    <span class="header">{cell.position.y}</span>
                  </Show>
                  <Cell cell={cell} click={clickCell}></Cell>
                </div>
              )}
            </For>
          </div>
        )}
      </For>
    </>
  );
}

export default Grid;
